### ISSUE TITLE
Scumm games cursor glitch (again) 

### ISSUE THREAD

**Issue by Urthaug78** [libretro/scummvm#62] opened 2024-08-17 14:02 UTC
I'm here again to re-report this strange bug behaviour with scumm engine games (except for the the FM-Town versions): when hit F1 to enter Retroarch menu and then leave the cursor become glitchy. The problem is present ONLY when using an overlay... 

Retroarch version: 1.19.1
ScummVM: last git.

**Comment by illando** [comment] 2024-08-21 08:26
Hi @Urthaug78 , I can confirm the bug is present, but it’s not related to pressing F1. It’s the toggling of any kind of overlay.
I can also report that it’s related to Hardware Acceleration option, if you turn it off going to: Core Options > Video Settings the cursor will be fine also toggling on/off the Overlay.

![IMG_5426](https://github.com/user-attachments/assets/e628a45c-55d1-4d48-b556-64d52b059aed)
![IMG_5425](https://github.com/user-attachments/assets/6c0af456-1ab0-4e8f-aef5-e405f06fe5a3)

**Comment by spleen1981** [comment] 2024-09-16 08:09
Hi, can you test [this build](https://git.libretro.com/libretro/scummvm/-/pipelines/300173)? You need to chose your platform, as it is not mentioned in the issue, and select "Download".

**Comment by Urthaug78** [comment] 2024-09-16 16:56
Hi, tested winx64 version with RetroArch 1.15.0. Loaded Maniac Mansion and Indiana Jones And The Fate Of Atlantis DOS versions. The problem seems to be gone.

**Comment by spleen1981** [comment] 2024-09-16 21:36
fixed by 668e2b66affdd6cadb5c8f1717a2dc30fcbcbffb

**Closed as completed by spleen1981** 2024-09-16 21:36 UTC

**Comment by illando** [comment] 2024-09-16 22:22
@spleen1981 tested the android-arm64-v8a, osx-arm64 and osx-x64 and I can confirm the problem is fixed!
Thanks a lot!
