### ISSUE TITLE
Hopkins FBI & Versailles crash on Android

### ISSUE THREAD

**Issue by triggerthehorizon** [libretro/scummvm#23] opened 2023-03-31 11:53 UTC
Hopkins FBI & Versailles crash on Android. The screen turns black and hangs for 10 seconds before RetroArch crashes. This happens on Android but not on windows. I am using the latest core and assets (using the core and system file downloader in RA)

**Comment by i30817** [comment] 2023-04-01 03:24
You should probably check if the same happens in upstream scummvm in android. Scummvm is not perfect in all engines, some are neglected or were never that complete.

**Comment by triggerthehorizon** [comment] 2023-04-01 10:21
Those two games work fine on official scummvm for Android

**Comment by i30817** [comment] 2023-04-01 12:02
'fakes'? Did you mean 'games' there?

Anyway, i'm on linux 64 bits and Versailles doesn't crash here either. I can't test HFBI, since i don't have it.

**Comment by triggerthehorizon** [comment] 2023-04-01 12:09
I did mean games, sorry, I can’t type on an Iphone 😵‍💫

**Comment by triggerthehorizon** [comment] 2023-04-01 12:17
I remember reporting those two bugs to the developer of the diablodiab Scummvm core and he had implemented a fix that worked

**Comment by triggerthehorizon** [comment] 2023-04-01 12:18
I believe he said it was a timing issue…

**Comment by spleen1981** [comment] 2023-04-01 12:31
@triggerthehorizon can you provide for both crashes the retroarch logs with debug level set for both frontend and core?

> Those two games work fine on official scummvm for Android

Did you check with the current [daily build](https://buildbot.scummvm.org/#/dailybuilds) of master branch?

> I remember reporting those two bugs to the developer of the diablodiab Scummvm core and he had implemented a fix that worked

All fixes [within libretro core backend tree] from that repo are already merged here.

**Comment by diablodiab** [comment] 2023-04-02 14:36
The fix was a workaround. I narrowed it down to a timing issue related to a delay. Patching out that delay appeared to fix the issue. But it was never properly addressed :)

https://github.com/diablodiab/libretro-scummvm-backend/blob/main/patches/android_fix_hopkins.patch

**Comment by spleen1981** [comment] 2023-04-02 16:05
> The fix was a workaround.

Agree, can't be a suitable solution.

@triggerthehorizon is the speed hack (now 'Allow Timing Inaccuracies') setting enabled?

**Comment by spleen1981** [comment] 2023-04-23 00:00
fixed by 2fd912be5964758d7ed3e77a55bf3a3be695a39d

**Comment by i30817** [comment] 2023-04-23 09:10
This definitely needs to be mentioned upstream i think, if it happens there. A optimization breaking compiled code is probably a compiler problem and scummvm is probably more likely to be able to track it down / manage to fill in the gcc bug tracker.

**Comment by spleen1981** [comment] 2023-04-23 10:26
Not happening with standalone scummvm, afaik.
Root cause can be upstream code, libretro implementation, a combination of the two or compiler version itself, hard to say without a deep (and time consuming) investigation, as there is no clear info in standard build tombstones regarding where the code fails.
So if the fix is confirmed to be working, this becomes a low priority topic to be investigated, as per TODO comment line already in the makefile.

**Comment by triggerthehorizon** [comment] 2023-04-23 15:28
Fix working here. Thank you!

**Closed as completed** 2023-04-23 15:46 UTC
